claude-glm() {
  ANTHROPIC_BASE_URL="https://api.z.ai/api/anthropic" \
  ANTHROPIC_AUTH_TOKEN="***REMOVED-GLM-KEY***" \
  API_TIMEOUT_MS="3000000" \
  ANTHROPIC_DEFAULT_OPUS_MODEL="GLM-5.2[1m]" \
  ANTHROPIC_DEFAULT_SONNET_MODEL="GLM-5.2[1m]" \
  ANTHROPIC_DEFAULT_OPUS_MODEL="glm-4.5-air" \
  CLAUDE_CODE_AUTO_COMPACT_WINDOW="1000000" \
  claude "$@"

}
